version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
      - run:
          name: Get Ready For Unit Tests
          working_directory: ~/project/app/logs
          command: |
            echo "" > debug.log
            echo "" > error.log
      - run:
          name: Run Unit Tests
          working_directory: ~/project/
          command: |
            coverage run -m unittest
            coverage html -d artifacts/test_results
            coverage xml -o test_results/test_results.xml
            coverage report -m
            coveralls
          environment:
            FLASK_ENV: Testing
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: artifacts/test_results
workflows:
  build_test:
    jobs:
      - build_and_test