version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            mkdir logs
            cd logs
            echo "" > debug.log
            echo "" > error.log
            sudo coverage run -m unittest discover
            sudo coverage report
            sudo coverage html
            sudo coveralls
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - build_and_test