version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            python3 -m venv venv
            . venv/bin/activate
            sudo pip install -r requirements.txt
      - run:
          name: Get Ready For Unit Tests
          working_directory: ~/project/app/logs
          command: |
            echo "" > debug.log
            echo "" > error.log
      - run:
          name: Run Unit Tests
          working_directory: ~/project/
          command: |
            mkdir test-reports
            coverage run -m unittest
            coverage report && coverage xml -o test-reports/coverage.xml
            coveralls
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - build_and_test