version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install -r requirements.txt
      - run:
          name: Get Ready For Unit Tests
          working_directory: ~/project/app/logs
          command: |
            echo "" > debug.log
            echo "" > error.log
      - run:
          name: Run Unit Tests
          working_directory: ~/project/
          command: |
            mkdir htmlcov
            coverage run -m unittest
            coverage report -m
            coverage html -d job_results
            coveralls
      - store_artifacts:
          path: job_results
      - store_test_results:
          path: job_results
workflows:
  build_test:
    jobs:
      - build_and_test